package com.njackson.ui.settings

data class SettingsUiState(
    val units: String = "1",
    val refreshInterval: String = "103000",
    val indoorMode: Boolean = false,
    val enableTracks: Boolean = true,
    val advancedGpx: Boolean = false,
    val exportEmail: String = "",
    val tcxActivity: String = "Biking",
    val activityRecognition: Boolean = false,
    val activityWalking: Boolean = false,
    val bleNames: List<String> = List(6) { "" },
    val bleAddresses: List<String> = List(6) { "" },
    val hrmMax: String = "0",
    val hrmZone: String = "0",
    val pebbleHrm: Boolean = false,
    val wheelPreset: String = "",
    val wheelSize: String = "",
    val liveTracking: Boolean = false,
    val liveUrl: String = "",
    val liveToken: String = "",
    val liveDevice: String = "",
    val liveMmt: Boolean = false,
    val liveMmtLogin: String = "",
    val liveMmtPassword: String = "",
    val oruxAuto: String = "disable",
    val stravaSession: String = "",
    val stravaAuto: String = "disable",
    val debug: Boolean = false,
    val pressureAvailable: Boolean = false,
    val geoidHeight: Float = 0f,
)
